name: real_estate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '3.6.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_svg: ^2.0.4
  google_fonts: ^6.2.1
  rename: ^3.0.2
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  dotted_border: ^2.1.0
  #dots_indicator: ^2.1.0
  carousel_slider: ^5.0.0
  expandable_page_view: ^1.0.17
  #scroll_navigation: ^1.3.2
  readmore: ^3.0.0
  #transformable_list_view: ^0.3.0
  #animation_list: ^2.2.1
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  # for state management
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  #flutter_credit_card: ^3.0.6
  webview_flutter: ^4.8.0
  timeago: ^3.7.0
  http: ^1.2.2
  flutter_timer_countdown: ^1.0.7
  flutter_rating_bar: ^4.0.1
  html: ^0.15.4
  dotted_line: ^3.2.2
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  file_picker: ^8.0.6
  bottom_bar: ^2.0.3
  syncfusion_flutter_sliders: ^27.1.57
  chips_choice: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0
  shimmer: ^2.0.0
  fluttertoast: ^8.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icons/
   - assets/images/
#   - assets/stripe/
   - assets/Yash/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21